---
name: Simple Compute Engine Usage
docPath: ../output
views:
  -
    name: overview
    layers: ["zone", "instance-group"]
nodes:
  -
    name: Service Instance
    components:
      - 'Compute Engine'
    clusters:
      - 'zone:platform'
      - 'instance-group:a'
  -
    name: Heartbeat and Snapshot System
    components:
      - 'Compute Engine'
    clusters:
      - 'zone:platform'
      - 'instance-group:b'
relations:
  -
    type: network
    components:
      - 'browser?icon=browser'
      - 'Cloud DNS?icon=gcp-cloud-dns'
      - 'zone:platform:Cloud Load Balancing?icon=gcp-cloud-load-balancing'
  -
    type: network
    components:
      - 'zone:platform:cloud load balancing?icon=gcp-cloud-load-balancing'
      - 'Service Instance:compute engine?icon=gcp-compute-engine'
  -
    type: network
    components:
      - 'Service Instance:compute engine?icon=gcp-compute-engine'
      - 'Heartbeat and Snapshot System:compute engine?icon=gcp-compute-engine'
      - 'Service Instance:compute engine?icon=gcp-compute-engine'
  -
    type: network
    components:
      - 'Service Instance:compute engine?icon=gcp-compute-engine'
      - 'zone:platform:Persistent Disk Snapshot?icon=gcp-persistent-disk'
