name: build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  job-test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: [1.17]
    steps:
      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go_version }}

      - name: Setup
        run: |
          sudo apt-get update
          sudo apt-get install graphviz
          sudo pip install codecov

      - name: Check out source code
        uses: actions/checkout@v2

      - name: Get branch
        id: get_branch
        run: echo ::set-output name=GITHUB_BRANCH::${GITHUB_REF/refs\/heads\//}

      - name: Test
        run: make ci

      - name: Update ndiag documents
        run: make ci_doc

      - uses: EndBug/add-and-commit@v7
        with:
          add: 'docs/ example/'

      - name: Run codecov
        run: codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Run octocov
        uses: k1LoW/octocov-action@v0
