name: build

on: push

jobs:
  job-test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: [1.14, 1.15]
    steps:
      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go_version }}

      - name: Setup
        run: |
          sudo apt-get update
          sudo apt-get install graphviz
          sudo pip install codecov

      - name: Check out source code
        uses: actions/checkout@v2

      - name: Get branch
        id: get_branch
        run: echo ::set-output name=GITHUB_BRANCH::${GITHUB_REF/refs\/heads\//}

      - name: Update ndiag documents
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          env PATH=`go env GOPATH`/bin:$PATH make ci_doc
        env:
          GITHUB_BRANCH: ${{ steps.get_branch.outputs.GITHUB_BRANCH }}

      - name: Test
        run: make ci

      - name: Run codecov
        run: codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
